export const BITCOIN_TYPE = "BITCOIN_TYPE";
export const BITCOIN_CASH_TYPE = "BITCOIN_CASH_TYPE";
export const BITCOIN_SV_TYPE = "BITCOIN_SV_TYPE";
export const LITECOIN_TYPE = "LITECOIN_TYPE";
export const DASH_TYPE = "DASH_TYPE";
